name: C Project CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-raylib
            mingw-w64-x86_64-gdb

      - name: Build (Debug)
        shell: cmd
        run: compile.bat debug false "C:\msys64\mingw64"

      - name: Build (Release)
        shell: cmd
        run: compile.bat release false "C:\msys64\mingw64"