name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache MSYS2
        uses: actions/cache@v4
        with:
          path: C:\msys64
          key: msys2-${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: |
            msys2-${{ runner.os }}-

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-raylib
            mingw-w64-x86_64-binutils

      - name: Build Debug
        shell: msys2 {0}
        run: ./compile.bat debug false

      - name: Build Release
        shell: msys2 {0}
        run: ./compile.bat release false

      - name: Run Test Build
        shell: msys2 {0}
        run: ./compile.bat test false
